# Generated by Django 6.0.4 on 2026-05-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('salario_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icone', models.CharField(max_length=50)),
                ('estrelas', models.IntegerField(default=4)),
            ],
        ),
    ]
