# Generated by Django 6.0.4 on 2026-05-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissao',
            name='icone',
            field=models.ImageField(max_length=50, upload_to=''),
        ),
    ]
