# Generated by Django 6.0.4 on 2026-05-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='alto_contraste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idioma',
            field=models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='reduzir_animacoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tamanho_fonte',
            field=models.CharField(choices=[('normal', 'Normal'), ('grande', 'Grande'), ('muito_grande', 'Muito grande')], default='normal', max_length=20),
        ),
    ]
