# Generated by Django 6.0.4 on 2026-05-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0005_perfil_alto_contraste_perfil_idioma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
    ]
