# Generated by Django 6.0.4 on 2026-05-11 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0006_alter_curso_avaliacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profissao',
            name='estrelas',
        ),
        migrations.AddField(
            model_name='favorito',
            name='profissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kapp.profissao'),
        ),
        migrations.AddField(
            model_name='profissao',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profissao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kapp.curso'),
        ),
        migrations.AlterField(
            model_name='profissao',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='profissoes/icones/'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', False)), fields=('usuario', 'curso'), name='unique_favorito_curso'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(condition=models.Q(('profissao__isnull', False)), fields=('usuario', 'profissao'), name='unique_favorito_profissao'),
        ),
    ]
