# Generated by Django 6.0.4 on 2026-05-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0008_alter_profissao_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias_cursos/')),
            ],
            options={
                'verbose_name': 'Categoria de Curso',
                'verbose_name_plural': 'Categorias de Cursos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProfissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias_profissoes/')),
            ],
            options={
                'verbose_name': 'Categoria de Profissão',
                'verbose_name_plural': 'Categorias de Profissões',
            },
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name': 'Profissão', 'verbose_name_plural': 'Profissões'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='kapp.categoriacurso'),
        ),
        migrations.AddField(
            model_name='profissao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissoes', to='kapp.categoriaprofissao'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
