# Generated by Django 6.0.4 on 2026-05-21 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0009_categoriacurso_categoriaprofissao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteUsoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagens_hoje', models.PositiveIntegerField(default=0)),
                ('data_contagem', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limite_bot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limite de Uso do Bot',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesses', models.CharField(blank=True, max_length=500, verbose_name='Áreas de interesse')),
                ('habilidades', models.CharField(blank=True, max_length=300, verbose_name='Habilidades selecionadas')),
                ('valores_carreira', models.CharField(blank=True, max_length=300, verbose_name='Valores de carreira')),
                ('estilo_trabalho', models.CharField(blank=True, choices=[('solo', 'Sozinho, com foco e autonomia'), ('equipe', 'Em equipe, colaborando com outros'), ('publico', 'Com o público, atendendo pessoas'), ('campo', 'Em campo, com atividades práticas')], max_length=20, verbose_name='Estilo de trabalho')),
                ('escolaridade', models.CharField(blank=True, choices=[('tecnico', 'Curso técnico'), ('graduacao', 'Graduação'), ('pos', 'Pós-Graduação / Especialização'), ('mestrado', 'Mestrado ou Doutorado')], max_length=20, verbose_name='Escolaridade pretendida')),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_questionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta do Questionário',
                'verbose_name_plural': 'Respostas do Questionário',
            },
        ),
        migrations.CreateModel(
            name='SessaoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('questionario', 'Questionário'), ('direto', 'Direto')], default='direto', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'KappaBot')], max_length=10)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='kapp.sessaochat')),
            ],
            options={
                'verbose_name': 'Mensagem do Chat',
                'ordering': ['criado_em'],
            },
        ),
    ]
