# Generated by Django 6.0.4 on 2026-05-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapp', '0010_limiteusobot_respostaquestionario_sessaochat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='areas_atuacao/')),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'Áreas de Atuação',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='curso',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='profissao',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='profissao',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='profissoes/icones/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='kapp.areaatuacao'),
        ),
        migrations.AlterField(
            model_name='profissao',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissoes', to='kapp.areaatuacao'),
        ),
        migrations.DeleteModel(
            name='CategoriaCurso',
        ),
        migrations.DeleteModel(
            name='CategoriaProfissao',
        ),
    ]
